service: cps

provider:
  name: aws
  runtime: go1.x
  endpointType: REGIONAL

package:
 exclude:
   - ./**
 include:
   - ./bin/cps-**

functions:
  root:
    handler: bin/cps-root
    events:
      - http:
          path: /
          method: GET
  repo:
    handler: bin/cps-repo
    events:
      - http:
          path: /repo/{slug}
          method: GET
      - http:
          path: /{region}/repo/{slug}
          method: GET
